### ISSUE TITLE
Error in pg.mark_doublets

### ISSUE THREAD

**Issue by Zifeng-L** [lilab-bcb/pegasus#112]
Hi, here.
I found that pegasus added scrublet as doublet detection API. However, when using the pg.mark_doublets, there were something wrong.
![image](https://user-images.githubusercontent.com/53402047/97437682-cc4ab380-195e-11eb-98ae-b1db36aa112e.png)
![image](https://user-images.githubusercontent.com/53402047/97437742-e2587400-195e-11eb-9504-7e6c712a9379.png)
Then I checked the data.obs. It seemed that the demux_type had been marked. 
![image](https://user-images.githubusercontent.com/53402047/97438004-32cfd180-195f-11eb-9264-7ce1149a7751.png)
Can anyone help me? Can I just use the demux_type to filter cells?

**Comment by yihming** [comment]
Hi @Zifeng1995 .

In the most recent release of Pegasus, we've replaced Scrublet by our own way of doublet inference, which is similar to the mechanism of Scrublet but with an automated inference based on doublet scores.

Please see the APIs at https://pegasus.readthedocs.io/en/stable/api/index.html#doublet-detection.

We've also provided a tutorial on doublet detection at https://pegasus.readthedocs.io/en/stable/_static/tutorials/doublet_detection.html.

**Comment by yihming** [comment]
Please feel free to reach out to us if you still encounter problems, and reopen this issue.
