### ISSUE TITLE
"X_" should be "W_"

### ISSUE THREAD

**Issue by slowkow** [lilab-bcb/pegasus#129]
The documentation is wrong:

https://github.com/klarman-cell-observatory/pegasus/blob/e551102fb8b5c1a1f3b21d1c75e68006a65c1ffe/pegasus/tools/clustering.py#L34

Notice:

https://github.com/klarman-cell-observatory/pegasus/blob/e551102fb8b5c1a1f3b21d1c75e68006a65c1ffe/pegasus/tools/clustering.py#L62-L65

Same for `pg.leiden()`

**Comment by bli25** [comment]
@slowkow , thanks for reporting this! 

we have changed the documentation to "Keyword ``'X_' + rep`` must exist in ``data.obsm`` and nearest neighbors must be calculated so that affinity matrix ``'W_' + rep`` exists in ``data.uns``".
