### ISSUE TITLE
RuntimeError: implement_array_function method already has a docstring

### ISSUE THREAD

**Issue by slowkow** [lilab-bcb/pegasus#14]
I would like to make a contribution to pegasus.

To do that, I need to install it from the code in the git repo.

```
Ubuntu 18.04.3 LTS
Python 3.7.5
```

Here are my steps (on the bcb-data server at MGH):

```
git clone git@github.com:klarman-cell-observatory/pegasus.git
cd pegasus
python setup.py install
```

There are many issues. For example, I need to install pybind11 by myself.

```
conda install pybind11
```

Still, after installing pybind11 I still get errors with `python setup.py install`:

```
Running fisher-0.1.9/setup.py -q bdist_egg --dist-dir /tmp/easy_install-f6fmt_sl/fisher-0.1.9/egg-dist-tmp-fr0eji09
/home/ks38/.conda/envs/pegasus-kamil/lib/python3.7/site-packages/setuptools/dist.py:476: UserWarning: Normalizing 'v0.1.9' to '0.1.9'
  normalized_version,
warning: no files found matching 'README.rst'
UPDATING build/lib.linux-x86_64-3.7/fisher/_version.py
set build/lib.linux-x86_64-3.7/fisher/_version.py to 'v0.1.9'
Traceback (most recent call last):
  File "/home/ks38/.conda/envs/pegasus-kamil/lib/python3.7/site-packages/setuptools/sandbox.py", line 154, in save_modules
 
RuntimeError: implement_array_function method already has a docstring

During handling of the above exception, another exception occurred:


RuntimeError: implement_array_function method already has a docstring
```

To resolve this, here is what I had to do.

```
pip install fisher anndata Cython docopt colorcet hvplot plotly matplotlib loompy
```

Then running `python setup.py install` seems to work. I had exactly the same experience on macOS 10.14 and the same commands resolved the issue.

Whew! This is very confusing 😰

**Comment by yihming** [comment]
Thanks for reaching!

For the general installation, please follow our [installation manual](https://pegasus.readthedocs.io/en/latest/installation.html).

To install pegasus github version, besides installing prerequisite libraries in the installation manual above, and given that you are installing it in a conda environment, please do the following:

```
sudo apt install git
git clone git@github.com:klarman-cell-observatory/pegasus.git
cd pegasus
pip install .
```

Using `python setup.py` usually requires you download some dependency packages on your own.

We've just add this development version installation guide on Pegasus documentation website. Please check it out [here](https://pegasus.readthedocs.io/en/latest/installation.html#development-version).
