### ISSUE TITLE
faster differential expression analysis

### ISSUE THREAD

**Issue by slowkow** [lilab-bcb/pegasus#15]
For a scRNA-seq dataset with 145,741 cells, 28,248 genes, and 41 clusters, here are the runtimes for two different approaches to test for differential gene expression:

```
python pegasus  1072 seconds
     R presto     32 seconds
```

Both approaches should generate similar statistics, but it seems that presto is 33.5 times faster.

I would like ask if you might consider copying the strategy from the [presto] package by @ilyakorsunsky to make this step faster in pegasus.

I have an inkling that the statistics from these two approaches might not be identical. I haven't yet had a chance to test this.

Also, you might consider a different completely approach to differential gene expression. Reducing the single-cell data to "pseudobulk" by summing all the cells in a cluster in a channel prior to differential expression seems to be a good approach. See [Lun and Marioni 2017][2] for details.

[2]: https://academic.oup.com/biostatistics/article/18/3/451/2970368
[presto]: https://github.com/immunogenomics/presto

**Comment by bli25** [comment]
Hi Kamil,

Thanks a lot for bringing this issue up. Yes, we are aware of presto
package and are happy to work with Ilya on incorporating it to Pegasus.

Can you let me know what DE analyses you have done in Pegasus and presto?
In addition, have you tried the multi-threading options in Pegasus?

Thanks,
Bo


Bo Li, Ph.D.
Director, Bioinformatics and Computational Biology Program, Center for
Immunology and Inflammatory Diseases, Massachusetts General Hospital
Member of the Faculty, Harvard Medical School
Associated Scientist, Klarman Cell Observatory, Broad Institute of MIT &
Harvard
149 13th Street, Room 8214, Charlestown, MA 02129

**Comment by slowkow** [comment]
I ran with default settings for both packages. So, Pegasus was using multiple threads (I guess 8 on my laptop).

I'm working on a new version of `calculate_auc_values()` for Pegasus, and I got it down to 213 seconds (single thread) from the original 1072 seconds (8 threads) just by rearranging some loops and computing the U statistic myself. There is still room for improvement.

**Comment by bli25** [comment]
Hi Kamil,

Wow, that is fantastic!

Best,
Bo

Bo Li, Ph.D.
Director, Bioinformatics and Computational Biology Program, Center for
Immunology and Inflammatory Diseases, Massachusetts General Hospital
Member of the Faculty, Harvard Medical School
Associated Scientist, Klarman Cell Observatory, Broad Institute of MIT &
Harvard
149 13th Street, Room 8214, Charlestown, MA 02129

**Comment by bli25** [comment]
@slowkow , #132  addressed this issue. Thus, I'll close it.
