### ISSUE TITLE
qcviolin separated plots?

### ISSUE THREAD

**Issue by YichaoOU** [lilab-bcb/pegasus#176]
Hello,

I'm wondering why the plot is separated into two parts?

```
pg.qc_metrics(data, percent_mito=10,mito_prefix="mt-")
pg.qcviolin(data, plot_type='gene')
```

Something I did wrong?

![Screen Shot 2021-03-18 at 6 49 12 PM](https://user-images.githubusercontent.com/19987406/111711891-a3965e00-881a-11eb-8f1e-acb7ca25464c.png)

Thanks,
Yichao

**Comment by yihming** [comment]
Hello,

Is it possible to attach the content of `data.uns["df_qcplot"]` after running `pg.qcviolin`?

Also `data.uns["df_qcplot"]["Channel"].cat.categories`.

**Comment by yihming** [comment]
Hello @YichaoOU ,

Just follow up with your issue on `qc_violin`.

After inspecting your issue once again, I noticed that it can be resolved by changing `n_violin_per_panel` argument of `qc_violin` function (see [documentation](https://pegasus.readthedocs.io/en/stable/api/pegasus.qcviolin.html)). 

This argument has default `8`, which generates every 8 violin plots within one figure. If say you want to include all the 10 violins above into one figure, simply add `n_violin_per_panel=10` to your `qc_violin` call.

Hope it helps.


Sincerely,
Yiming
