### ISSUE TITLE
the ipynb tutorial is too big to render

### ISSUE THREAD

**Issue by slowkow** [lilab-bcb/pegasus#18]
The tutorial file is too big to render. I would recommend converting it to a small HTML file with PNG images instead of interactive plotly figures.

![image](https://user-images.githubusercontent.com/209714/71115547-2bb53000-21a0-11ea-966f-3137bfbe5ac7.png)

The plotly figure are the cause of this issue. Each SVG contains an uncompressed text string that has all of the coordinates of all of the data points. That's why it is 35 MB.

I'll try to render a new one for you that is much smaller, so we can view it more easily.

**Comment by yihming** [comment]
It's already converted to html files, and posted on Pegasus documentation website. Please check them out [here](https://pegasus.readthedocs.io/en/latest/tutorials.html).

**Comment by yihming** [comment]
We put their ipynb versions here just to make the collaborative editing easier. We can move them in a dedicated repository if needed.

**Comment by slowkow** [comment]
OK, [the HTML version](https://pegasus.readthedocs.io/en/latest/_static/tutorials/pegasus_analysis.html) you shared renders on my laptop in 35 seconds. Just letting you know.

If I find the time to make a smaller version, I will share it here and you can decide whether you'd like to use it on the website.

If we feel that the interactive figures are important, then I would also consider trying [datashader](https://holoviz.org/tutorial/Basic_Plotting.html) to make the file size smaller and render faster with millions of data points.

![image](https://user-images.githubusercontent.com/209714/71123689-35935f00-21b1-11ea-8370-a51b0ec13cf7.png)

**Comment by yihming** [comment]
Thanks for the sharing. I'll definitely try datashader to see if it helps.

**Comment by yihming** [comment]
However, the scPlot functions seem not support datashading

**Comment by yihming** [comment]
scPlot supports annother way other than datashading for reducing image size, which I'm trying. BTW, does [the other tutorial](https://pegasus.readthedocs.io/en/latest/_static/tutorials/sn_analysis.html) also take a long time on loading?

**Comment by slowkow** [comment]
The other tutorial (`"./mouse/exp_demux.h5sc"`) renders after 6.7 seconds on my laptop, so I guess it is OK as it is.

![image](https://user-images.githubusercontent.com/209714/71189851-78a50f00-2251-11ea-85b2-5ddc1432c0d3.png)

**Comment by yihming** [comment]
Pegasus now uses `matplotlib` rather than `bokeh` for plotting. The rendering issue should have gone.
