### ISSUE TITLE
Issue while trying to run pegasus_analysis.ipynb

### ISSUE THREAD

**Issue by rgranit** [lilab-bcb/pegasus#182]
While attempting to run pegasus_analysis.ipynb I encountered the following issue in during the batch correction section:

`TypeError: harmonize() got an unexpected keyword argument 'n_jobs_kmeans'`

 Pegasus was installed according to the requirements defined by Cumulus (`harmony-pytorch=0.1.6`)

Thanks!

**Comment by yihming** [comment]
Hi @rgranit , could you please provide your `pegasus` version when running the notebook?

**Comment by yihming** [comment]
In general, when using `harmony-pytorch` v0.1.6, you'll need to upgrade your `pegasus` to v1.3.0 to have a compatible interface with it.

**Comment by rgranit** [comment]
@yihming I'm using `pegasus 1.2.0` I'll try to upgrade to v1.3.0 and revert..

**Comment by rgranit** [comment]
Thanks, after installing v1.3.0 harmony works
