### ISSUE TITLE
Seurat? Conditions to channels?

### ISSUE THREAD

**Issue by s849** [lilab-bcb/pegasus#183]
Hello,

Thank you for developing Pegasus. I am wondering if it is possible to convert a Seurat object into Pegasus object and transfer the conditions as "Channels" in Pegasus to be able to use the Pegasus functions for doing DGE analysis across conditions/channels?

**Comment by bli25** [comment]
@s849 . You can use Seurat to convert a Seurat object into a h5ad file. Pegasus can load h5ad file using pg.read_input().

Hope it helps.
