### ISSUE TITLE
Pegasus only compatible with old versions of scipy

### ISSUE THREAD

**Issue by tariqdaouda** [lilab-bcb/pegasus#19]
When trying to install pegasuspy with newer versions of scipy, one gets:

scipy 1.4.1 is installed but scipy<1.3 is required by {'pegasuspy'}

**Comment by yihming** [comment]
This is because anndata 0.6.22.post1 has conflict with new scipy versions, especially the slicing. For details, please check out [this issue](https://github.com/theislab/anndata/issues/194).

But as anndata 0.7.1 was released last week, we may give it a try, and see if we can allow newer scipy.

**Comment by yihming** [comment]
Please try pegasuspy 0.17.0.
