### ISSUE TITLE
Bug when saving net_FLE 3D output to object

### ISSUE THREAD

**Issue by gabprg** [lilab-bcb/pegasus#2]
Hi there!
Was just trying to compute the FLE in 3D, and I ran into the following error:

> 1236     Y_init = np.zeros((data.shape[0], 2), dtype=np.float64)
> -> 1237     Y_init[selected, :] = X_fle
>    1238     Y_init[~selected, :] = net_train_and_predict(
>    1239         X, X_fle, X_full[~selected, :], net_alpha, random_state, verbose=True
> 
> ValueError: shape mismatch: value array of shape (6588,3) could not be broadcast to indexing result of shape (6588,2)

Looks like the function assumes it's going to be in 2D, would be great if you could fix by modifying that in the case when is3d = True. Thanks!

Gabi

**Comment by yihming** [comment]
Hi Gabi,

Thank you for catching this bug! 

The commit 328f76d has fixed the bug. Please check it out to see if pegasus works properly on 3D Net-FLE. It will be included in our next release.



Sincerely,
Yiming
