### ISSUE TITLE
Is there any academic paper for pegasus?

### ISSUE THREAD

**Issue by tangmaomao16** [lilab-bcb/pegasus#222]
I want to cite pegasus, but I cannot find the academic paper for pegasus. Is there any academic paper for pegasus? I mean the first paper about pegasus.

**Comment by yihming** [comment]
Hi @tangmaomao16 ,

The paper about Pegasus is ["Cumulus provides cloud-based data analysis for large-scale single-cell and single-nucleus RNA-seq"](https://www.nature.com/articles/s41592-020-0905-x), which was published on Nature methods in 2020.

Hope it helps.


Sincerely,
Yiming
