### ISSUE TITLE
error when using aggregate_matrices to aggregate two multimodaldata

### ISSUE THREAD

**Issue by daisyyr** [lilab-bcb/pegasus#236]
Hi~Thanks for using such an useful tool
I've encountered some problems when using aggregate_matrices to aggregate two multimodaldata
My codes are as follows.
`data_all = pg.aggregate_matrices({'Sample': ['sample1', 'sample2'], 'Object': [data1, data2]})`
And I got an error as follows.
`RuntimeError                              Traceback (most recent call last)
<ipython-input-28-32feb68cbfb7> in <module>
----> 1 data_all = pg.aggregate_matrices({'Sample': ['sample1', 'sample2'], 'Object': [data1, data2]})

~/.conda/envs/pegasus_latest/lib/python3.8/site-packages/pegasusio/decorators.py in wrapper_timer(*args, **kwargs)
     10                 def wrapper_timer(*args, **kwargs):
     11                         start = time.perf_counter()
---> 12                         result = func(*args, **kwargs)
     13                         end = time.perf_counter()
     14                         message = f"Function '{func.__name__}' finished in {{:.{precision}f}}s.".format(end - start)

~/.conda/envs/pegasus_latest/lib/python3.8/site-packages/pegasusio/data_aggregation.py in aggregate_matrices(csv_file, restrictions, attributes, default_ref, append_sample_name, select_singlets, remap_string, subset_string, min_genes, max_genes, min_umis, max_umis, mito_prefix, percent_mito)
    208             if curr_data is not None:
    209                 curr_data._propogate_genome()
--> 210                 curr_data.filter_data(select_singlets = select_singlets, remap_string = remap_string, subset_string = subset_string, min_genes = min_genes, max_genes = max_genes, min_umis = min_umis, max_umis = max_umis, mito_prefix = mito_prefix, percent_mito = percent_mito)
    211                 curr_data._update_barcode_metadata_info(curr_row, attributes, append_sample_name)
    212                 aggrData.add_data(curr_data)

~/.conda/envs/pegasus_latest/lib/python3.8/site-packages/pegasusio/multimodal_data.py in filter_data(self, select_singlets, remap_string, subset_string, min_genes, max_genes, min_umis, max_umis, mito_prefix, percent_mito, focus_list, cache_passqc, uns_white_list)
    420                         mito_prefix = mito_dict.get(unidata.get_genome()),
    421                         percent_mito = percent_mito)
--> 422                 apply_qc_filters(unidata, uns_white_list=uns_white_list)
    423                 selected_barcodes = unidata.obs_names if selected_barcodes is None else selected_barcodes.union(unidata.obs_names)
    424             else:

~/.conda/envs/pegasus_latest/lib/python3.8/site-packages/pegasusio/qc_utils.py in apply_qc_filters(unidata, uns_white_list)
    163         unidata.obs.drop(columns=cols, inplace=True)
    164         if len(unidata.obsm) > 0:
--> 165             for key in unidata.obsm.keys():
    166                 if key not in ['X_spatial']:
    167                     del unidata.obsm[key]

~/.conda/envs/pegasus_latest/lib/python3.8/_collections_abc.py in __iter__(self)
    718 
    719     def __iter__(self):
--> 720         yield from self._mapping
    721 
    722 KeysView.register(dict_keys)

RuntimeError: dictionary changed size during iteration
`
When I deleted data1.obsm and data2.obsm,the code went well.
So what might be the problem? Is there anything I can do besides deleting obsm ?

**Comment by yihming** [comment]
Hi @daisyyr ,

Sorry for my late response... I just saw your issue.

This is a bug in PegasusIO package, which was fixed in v0.5.1 (see release notes [here](https://pegasusio.readthedocs.io/en/stable/#version-0-5-1-february-10-2022)).

So please upgrade the PegasusIO package in your Python environment to v0.5.1 or later.


Sincerely,
Yiming
