### ISSUE TITLE
highly_variable_features uses data.uns["Channels"]

### ISSUE THREAD

**Issue by joshua-gould** [lilab-bcb/pegasus#24]
If you update data.obs['Channel'], then data.uns['Channels'] is not automatically updated. Instead, highly_variable_features should get the unique values directly from  data.obs['Channel']

**Comment by zyzhanyong1995** [comment]
I have encountered the same problem. So I sincerely hope the author could solve this problem in the next updated version.

**Comment by yihming** [comment]
Thank you for reporting this issue! We'll definitely check and fix it.

**Comment by bli25** [comment]
@joshua-gould @zyzhanyong1995 , we have updated Pegasus code. Now users can provide any attribute for batch information using the 'batch' key in highly variable gene selection procedure. In addition, we eliminated 'Channels' to avoid the problem you have encountered. We will release the update in the next version.
