### ISSUE TITLE
L/S method is deprecated in version 1.4.5?

### ISSUE THREAD

**Issue by niehu2018** [lilab-bcb/pegasus#241]
Hi, 
I can not find the correct_batch function in pegasus version 1.4.5.
Is L/S method deprecated, and why?

Best

**Comment by yihming** [comment]
Hi @niehu2018 ,

Yes, this function is obsolete in v1.4.5, but is officially announced in v1.5.0 (See release notes [here](https://pegasus.readthedocs.io/en/stable/release_notes.html#version-1-5)). I apologize for this inconsistency.

Pegasus has already used Harmony algorithm by default for batch correction in its `pegasus cluster` command if enabling `--correct-batch-effect` option. In Pegasus API, it's [run_harmony](https://pegasus.readthedocs.io/en/stable/api/pegasus.run_harmony.html#pegasus.run_harmony) function, along with [other alternatives](https://pegasus.readthedocs.io/en/stable/api/index.html#batch-correction). And the [Batch Correction tutorial](https://pegasus-tutorials.readthedocs.io/en/latest/_static/tutorials/batch_correction.html) has also been updated accordingly.

By contrast, L/S method is less frequently used by users, and it only works well in the case that all batches have the similar cell type proportion. Therefore, we recommend using `run_harmony` for batch correction in general.

Hope it helps.


Sincerely,
Yiming

**Comment by niehu2018** [comment]
Thanks Yiming!

The L/S method seems to return a batch corrected matrix. That is what I want.
As some tools such as compass (https://github.com/YosefLab/Compass) need batch corrected gene expression as input,
Is there any way to get batch-corrected gene expression matrix?
I know the quantile normalization may help to correct batch.

Best

**Comment by bli25** [comment]
Hi Niehu,

You can still use the L/S method with Pegasus v1.4.4 or earlier.

Best,
Bo


Bo Li, Ph.D.
Senior Scientist, Data Science and Statistical Computing
Genentech, A Member of the Roche Group
