### ISSUE TITLE
How can I plot diffusion map by DC2 and DC3?

### ISSUE THREAD

**Issue by Zifeng-L** [lilab-bcb/pegasus#247]
Hi there! We tried to calculate diffusion map by `pg.diffmap(data)` and draw scatter by `pg.scatter(data,attrs=['louvain_labels'],basis='diffmap')`, the figure show the diffusion map with the component of 'DC1' and 'DC2'. I just want to know, how to get the figure showing the diffusion map with other components, for example 'DC2' and 'DC3'? Thank you for your help!

**Comment by bli25** [comment]
Hi @Zifeng-L , 

We have enabled this in Pegasus v1.7.0.

To plot DC2 and DC3, use `pg.scatter(data, attrs='louvain_labels', basis='diffmap', components=(2,3)`.

Best,
Bo

**Comment by Zifeng-L** [comment]
> Hi @Zifeng-L ,
> 
> We have enabled this in Pegasus v1.7.0.
> 
> To plot DC2 and DC3, use `pg.scatter(data, attrs='louvain_labels', basis='diffmap', components=(2,3)`.
> 
> Best, Bo

That‘s great！Thanks！
