### ISSUE TITLE
【Bug】leiden or louvain clustering error

### ISSUE THREAD

**Issue by Zifeng-L** [lilab-bcb/pegasus#256]
Hello there,

While using Pegasus version 1.7.0, I noticed that the API "pg.neighbors" updates the weight matrix and returns it to "data.obsp['W_rep']". However, the "pg.leiden" API still uses "data.uns['W_rep']". As a result, an error occurs.
```
pg.neighbors(data_scan, rep=scan_key)
pg.leiden(data_scan, rep=scan_key,resolution=1)
pg.umap(data_scan, rep=scan_key)
```

```
2023-02-20 13:15:57,870 - pegasus.tools.nearest_neighbors - INFO - Function 'get_neighbors' finished in 21.59s.
2023-02-20 13:16:00,935 - pegasus.tools.nearest_neighbors - INFO - Function 'calculate_affinity_matrix' finished in 3.06s.
2023-02-20 13:16:04,090 - pegasus.tools.graph_operations - INFO - Function 'construct_graph' finished in 3.14s.
---------------------------------------------------------------------------
BaseException                             Traceback (most recent call last)
Cell In[11], line 2
      1 pg.neighbors(data_scan, rep=scan_key)
----> 2 pg.leiden(data_scan, rep=scan_key,resolution=1)
      3 pg.umap(data_scan, rep=scan_key)

File /opt/conda/envs/pg_1.7.1/lib/python3.9/site-packages/pegasusio/decorators.py:12, in timer.<locals>.inner_decorator.<locals>.wrapper_timer(*args, **kwargs)
      9 @functools.wraps(func)
     10 def wrapper_timer(*args, **kwargs):
     11 	start = time.perf_counter()
---> 12 	result = func(*args, **kwargs)
     13 	end = time.perf_counter()
     14 	message = f"Function '{func.__name__}' finished in {{:.{precision}f}}s.".format(end - start)

File /opt/conda/envs/pg_1.7.1/lib/python3.9/site-packages/pegasus/tools/clustering.py:266, in leiden(data, rep, resolution, n_clust, n_iter, random_state, class_label)
    264 G = construct_graph(W)
    265 if resolution is not None:
--> 266     membership = _run_community_detection("leiden", leidenalg, G, resolution, random_state, n_iter)
    267 else:
    268     assert isinstance(n_clust, int)

File /opt/conda/envs/pg_1.7.1/lib/python3.9/site-packages/pegasus/tools/clustering.py:98, in _run_community_detection(algo, module, G, resolution, random_state, n_iter)
     96     diff = optimiser.optimise_partition(partition)
     97 else:
---> 98     partition = module.find_partition(
     99         G,
    100         partition_type,
    101         seed=random_state,
    102         weights="weight",
    103         resolution_parameter=resolution,
    104         n_iterations=n_iter,
    105     )
    106 return partition.membership

File /opt/conda/envs/pg_1.7.1/lib/python3.9/site-packages/leidenalg/functions.py:81, in find_partition(graph, partition_type, initial_membership, weights, n_iterations, max_comm_size, seed, **kwargs)
     79 if not weights is None:
     80   kwargs['weights'] = weights
---> 81 partition = partition_type(graph,
     82                            initial_membership=initial_membership,
     83                            **kwargs)
     84 optimiser = Optimiser()
     86 optimiser.max_comm_size = max_comm_size

File /opt/conda/envs/pg_1.7.1/lib/python3.9/site-packages/leidenalg/VertexPartition.py:840, in RBConfigurationVertexPartition.__init__(self, graph, initial_membership, weights, resolution_parameter)
    836   else:
    837     # Make sure it is a list
    838     weights = list(weights)
--> 840 self._partition = _c_leiden._new_RBConfigurationVertexPartition(pygraph_t,
    841     initial_membership, weights, resolution_parameter)
    842 self._update_internal_membership()

BaseException: Could not construct partition: Weight vector not the same size as the number of edges.
```

**Comment by Zifeng-L** [comment]
@yihming I'm struggling with this problem. Could you offer any help?

**Comment by yihming** [comment]
@Zifeng-L I tried at my side with my data, and they should work properly (even with Scanorama batch correction). And `pg.leiden` does check `obsp` rather than `uns` for the weight matrix (see [here](https://github.com/lilab-bcb/pegasus/blob/1.7.0/pegasus/tools/clustering.py#L262)).

Have you check if the shape of `data_scan.obsp['W_scanorama']` is of `(n_cells, n_cells)`? From the error message above, it seems that the issue is related to the weight matrix itself.

**Comment by Zifeng-L** [comment]
> @Zifeng-L I tried at my side with my data, and they should work properly (even with Scanorama batch correction). And `pg.leiden` does check `obsp` rather than `uns` for the weight matrix (see [here](https://github.com/lilab-bcb/pegasus/blob/1.7.0/pegasus/tools/clustering.py#L262)).
> 
> Have you check if the shape of `data_scan.obsp['W_scanorama']` is of `(n_cells, n_cells)`? From the error message above, it seems that the issue is related to the weight matrix itself.

I checked the shape of `data_scan.obsp['W_scanorama']` is of `(n_cells, n_cells)`.
![image](https://user-images.githubusercontent.com/53402047/220817532-e290df6c-b62b-4b0d-b4d2-e6e1b1791df3.png)

 Then I change the version of pegasus to 1.6.0, it works well.
So I just wondered what is the error with version 1.7.1. 

![1677124273344](https://user-images.githubusercontent.com/53402047/220817620-bb8714e8-6e14-4523-bb13-a475dcf53a00.png)

**Comment by yihming** [comment]
What is the version of `leidenalg` package in your environment?

**Comment by Zifeng-L** [comment]
leidenalg==0.8.10 louvain==0.7.1

**Comment by Zifeng-L** [comment]
In the pg 1.7.1 env, leidenalg==0.9.1 louvain==0.8.0
In the pg 1.6.0 env, leidenalg==0.8.10 louvain==0.7.1

**Comment by Zifeng-L** [comment]
> In the pg 1.7.1 env, leidenalg==0.9.1 louvain==0.8.0 In the pg 1.6.0 env, leidenalg==0.8.10 louvain==0.7.1

I tried to downgrade to leidenalg==0.8.10 louvain==0.7.1. It works!
