### ISSUE TITLE
counts.log_norm+scale in pegasus vs. scale.data in Seurat and scanpy

### ISSUE THREAD

**Issue by x1han** [lilab-bcb/pegasus#259]
Thank you for developing the excellent tool Pegasus. I am a beginner in single-cell genomics analysis and started with Seurat in R, later learned Scanpy in Python, but I find Pegasus more suitable for my needs. However, I am currently facing a challenge where I need to convert data between the three platforms Seurat, Scanpy, and Pegasus for my analysis. This has raised a question for me, which is that in Seurat and Scanpy, the subsequent analysis is based on scale.data, whereas in Pegasus, only the counts.log_norm matrix and the scale in obs are used. This has left me somewhat confused, so I would like to ask a few questions from my perspective, which may not be entirely correct.

1. In Seurat and scanpy, the ScaleData/scale step is usually accompanied by regress_out to remove batch effects or other sources of unrelated variance, resulting in a new matrix. In the Pegasus tutorial, however, it seems that the regress_out step is not necessary. Therefore, in Pegasus, is the regress_out step recommended?
2. In Seurat and scanpy, the ScaleData/scale step generates a new matrix that is relied upon for subsequent analysis. However, in Pegasus, the counts.log_norm matrix and the scale value in the obs attribute are generated. I would like to know the principle behind the generation of this scale value and whether it is similar to the ScaleData/scale step in Seurat and scanpy (I apologize for not finding it in the Pegasus code). Why is a new matrix not generated and instead the counts.log_norm matrix and scale value are used together? Also, how is the scale value used in subsequent analyses?
3. When I have a Seurat object, I can export the scale.data matrix from Seurat to create an anndata object in scanpy for downstream analysis. However, in Pegasus, I am not sure how to achieve this because the scale matrix seems to need to be separated into the counts.log_norm matrix and the scale value.

Thank you very much for your patience and answers. Pegasus is a great software, and I hope to develop new features based on Pegasus through future learning.
Hoping for a reply.

**Comment by yihming** [comment]
Hi @hxsci ,

Thanks for reaching out to us! It actually took me quite a while to finish my answer below, but hope it helps your case:

1. I checked Seurat's most recent [pbmc3k tutorial](https://satijalab.org/seurat/articles/pbmc3k_tutorial.html), and they recommend trying their data integration method in Seurat v3+, instead of `vars.to.regress` paramenter in `ScaleData` function. If you want to use regress out method, we do have this feature, with a [tutorial](https://pegasus-tutorials.readthedocs.io/en/latest/_static/tutorials/regress_out.html). The only difference is that our regress out is applied on PCA matrix, instead of the count matrix.
Alternatively, you can also try data integration methods that Pegasus provides. We have a [tutorial](https://pegasus-tutorials.readthedocs.io/en/latest/_static/tutorials/batch_correction.html) on this topic as well.

2. If you are talking about the step of standardization and truncating (based on max value) applied to highly variable genes, it's part of our `pca` function (see [here](https://github.com/lilab-bcb/pegasus/blob/c0413e5a38a14138eab20d56396838fb77e4dd8c/pegasus/tools/preprocessing.py#L669)), which is the same as SCANPY's `pp.scale` function.
The `data.obs['scale']` actually stores the scale factors for each cell, which are used to normalize their counts. So I think this is not related to the Scale Data step you mention.
Our `log_norm` function does generate a new count matrix with log-normalized counts, which you can fetch by
```
import pegasus as pg
data = pg.read_input("your-data-file")
data.get_matrix("counts.log_norm")
```
And its raw count matrix can be fetched by changing the last line above to `data.get_matrix("counts")`. So both raw and log normalized counts are stored. Then after selecting highly variable features/genes, a submatrix of shape (n_cells, n_hvg) is generated for applying `pca` function, which is `data.uns['_tmp_fmat_highly_variable_features']`. This matrix is not written to file when saving using `write_output` function, but you can see it at runtime by yourself.

3. For running Pegasus from a `scale.data` matrix created in Seurat, say you load it by
```
data = pg.read_input("your-data-file")
```
If your scale.data matrix is of shape (n_cell, n_gene), then you need to transfer your highly variable features to `data.var['highly_variable_features']` which is a boolean column. Otherwise, if the matrix is already of shape (n_cell, n_hvg), then simply set `data.var['highly_variable_features'] = True`.
Next, in PCA step, you need to specify `standardize` and `max_value` parameters as follows:
```
pg.pca(data, standardize=False, max_value=None)
```
so that it doesn't apply the scale data operation again.
After that, you can follow the standard downstream analysis with Pegasus.

Hope it helps.

**Comment by x1han** [comment]
Thank you for your reply. That's extremly helpful and I need to take some time to understand your answer.

**Comment by hxsci** [comment]
I have read your answer many times and spent time understanding it, which has been of great help to me.

Actually, we are performing single-cell trajectory analysis on our own dataset. However, the topology constructed by the pg.diffmap function does not produce satisfactory results, which prompts us to consider using the paga algorithm in the scanpy analysis pipeline. 
Following the paga workflow in scanpy, I found that paga takes the scaled gene expression matrix as input, like this:
`pgdata.select_matrix('counts')
adata_test = ad.AnnData(pgdata.X[:2000, :2000].toarray())
sc.pp.recipe_zheng17(adata_test)
adata_test.X

array([[-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 , -1.2051845 ],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 , -1.2051845 ],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 ,  0.6222586 ],
       ...,
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 ,  0.13764136],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 ,  0.76209235],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 , -0.5803896 ]], dtype=float32)`

Upon manually implementing a scaling procedure on the data and examining PAGA results both with and without scaling applied, it is evident that there is a significant dissimilarity between topologies ascertained under these conditions. 

`pgdata.select_matrix('counts')
adata_test = ad.AnnData(pgdata.X[:2000, :2000].toarray())

sc.pp.normalize_total(adata_test, target_sum=1e4)
sc.pp.log1p(adata_test)
sc.pp.scale(adata_test, max_value=10)
sc.tl.pca(adata_test, svd_solver='arpack')
sc.pp.neighbors(adata_test)
sc.tl.louvain(adata_test)
sc.tl.umap(adata_test)

sc.pl.umap(adata_test, color = 'louvain')

sc.tl.paga(adata_test)
sc.pl.paga(adata_test, color='louvain')
![image](https://user-images.githubusercontent.com/26381262/233828784-ac85b7c9-b916-484f-8a06-44a505af5d03.png)
`
`pgdata.select_matrix('counts')
adata_test = ad.AnnData(pgdata.X[:2000, :2000].toarray())

sc.pp.normalize_total(adata_test, target_sum=1e4)
sc.pp.log1p(adata_test)
# sc.pp.scale(adata_test, max_value=10)
sc.tl.pca(adata_test, svd_solver='arpack')
sc.pp.neighbors(adata_test)
sc.tl.louvain(adata_test)
sc.tl.umap(adata_test)

sc.pl.umap(adata_test, color = 'louvain')

sc.tl.paga(adata_test)
sc.pl.paga(adata_test, color='louvain')
![image](https://user-images.githubusercontent.com/26381262/233828796-8476465b-cea8-45be-bfae-7f138f709b69.png)
`

According to my understanding, providing a scaled gene expression matrix constitutes an essential input for PAGA analysis, which the Pegasus workflow does not provide by default. I have two plans to solve this:
1. Convert the Pegasus multimodal data object into an AnnData object using the to_anndata() function, then scale the data using sc.pp.scale from Scanpy before executing PAGA.
2. Construct a new scaled matrix by dividing the counts_log_norm matrix from Pegasus with the scale_data value or the PCA matrix, then convert this scaled matrix into an AnnData object and perform PAGA. 

I don't know if Plan 1 is meaningful, in fact, I prefer Plan 2, but I don't know how to implement it.

**Comment by hxsci** [comment]
I have read your answer many times and spent time understanding it, which has been of great help to me.

Actually, we are performing single-cell trajectory analysis on our own dataset. However, the topology constructed by the pg.diffmap function does not produce satisfactory results, which prompts us to consider using the paga algorithm in the scanpy analysis pipeline. 
Following the paga workflow in scanpy, I found that paga takes the scaled gene expression matrix as input, like this:
```python
pgdata.select_matrix('counts')
adata_test = ad.AnnData(pgdata.X[:2000, :2000].toarray())
sc.pp.recipe_zheng17(adata_test)
adata_test.X

array([[-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 , -1.2051845 ],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 , -1.2051845 ],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 ,  0.6222586 ],
       ...,
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 ,  0.13764136],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 ,  0.76209235],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 , -0.5803896 ]], dtype=float32)
```

Upon manually implementing a scaling procedure on the data and examining PAGA results both with and without scaling applied, it is evident that there is a significant dissimilarity between topologies ascertained under these conditions. 

```python
pgdata.select_matrix('counts')
adata_test = ad.AnnData(pgdata.X[:2000, :2000].toarray())

sc.pp.normalize_total(adata_test, target_sum=1e4)
sc.pp.log1p(adata_test)
sc.pp.scale(adata_test, max_value=10)
sc.tl.pca(adata_test, svd_solver='arpack')
sc.pp.neighbors(adata_test)
sc.tl.louvain(adata_test)
sc.tl.umap(adata_test)

sc.pl.umap(adata_test, color = 'louvain')

sc.tl.paga(adata_test)
sc.pl.paga(adata_test, color='louvain')
![image](https://user-images.githubusercontent.com/26381262/233828784-ac85b7c9-b916-484f-8a06-44a505af5d03.png)
```
```python
pgdata.select_matrix('counts')
adata_test = ad.AnnData(pgdata.X[:2000, :2000].toarray())

sc.pp.normalize_total(adata_test, target_sum=1e4)
sc.pp.log1p(adata_test)
# sc.pp.scale(adata_test, max_value=10)
sc.tl.pca(adata_test, svd_solver='arpack')
sc.pp.neighbors(adata_test)
sc.tl.louvain(adata_test)
sc.tl.umap(adata_test)

sc.pl.umap(adata_test, color = 'louvain')

sc.tl.paga(adata_test)
sc.pl.paga(adata_test, color='louvain')
![image](https://user-images.githubusercontent.com/26381262/233828796-8476465b-cea8-45be-bfae-7f138f709b69.png)
```

According to my understanding, providing a scaled gene expression matrix constitutes an essential input for PAGA analysis, which the Pegasus workflow does not provide by default. I have two plans to solve this:
1. Convert the Pegasus multimodal data object into an AnnData object using the to_anndata() function, then scale the data using sc.pp.scale from Scanpy before executing PAGA.
2. Construct a new scaled matrix by dividing the counts_log_norm matrix from Pegasus with the scale_data value or the PCA matrix, then convert this scaled matrix into an AnnData object and perform PAGA. 

I don't know if Plan 1 is meaningful, in fact, I prefer Plan 2, but I don't know how to implement it.

**Comment by x1han** [comment]
I have read your answer many times and spent time understanding it, which has been of great help to me.

Actually, we are performing single-cell trajectory analysis on our own dataset. However, the topology constructed by the pg.diffmap function does not produce satisfactory results, which prompts us to consider using the paga algorithm in the scanpy analysis pipeline. 
Following the paga workflow in scanpy, I found that paga takes the scaled gene expression matrix as input, like this:
```python
pgdata.select_matrix('counts')
adata_test = ad.AnnData(pgdata.X[:2000, :2000].toarray())
sc.pp.recipe_zheng17(adata_test)
adata_test.X

array([[-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 , -1.2051845 ],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 , -1.2051845 ],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 ,  0.6222586 ],
       ...,
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 ,  0.13764136],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 ,  0.76209235],
       [-0.03711927, -0.2085176 , -0.04109933, ..., -0.22517389,
        -0.0984643 , -0.5803896 ]], dtype=float32)
```

Upon manually implementing a scaling procedure on the data and examining PAGA results both with and without scaling applied, it is evident that there is a significant dissimilarity between topologies ascertained under these conditions. 

```python
pgdata.select_matrix('counts')
adata_test = ad.AnnData(pgdata.X[:2000, :2000].toarray())

sc.pp.normalize_total(adata_test, target_sum=1e4)
sc.pp.log1p(adata_test)
sc.pp.scale(adata_test, max_value=10)
sc.tl.pca(adata_test, svd_solver='arpack')
sc.pp.neighbors(adata_test)
sc.tl.louvain(adata_test)
sc.tl.umap(adata_test)

sc.pl.umap(adata_test, color = 'louvain')

sc.tl.paga(adata_test)
sc.pl.paga(adata_test, color='louvain')
```
![image](https://user-images.githubusercontent.com/26381262/233829766-4c0601a5-7cd3-4fe7-a08e-7b97a5553283.png)

```python
pgdata.select_matrix('counts')
adata_test = ad.AnnData(pgdata.X[:2000, :2000].toarray())

sc.pp.normalize_total(adata_test, target_sum=1e4)
sc.pp.log1p(adata_test)
# sc.pp.scale(adata_test, max_value=10)
sc.tl.pca(adata_test, svd_solver='arpack')
sc.pp.neighbors(adata_test)
sc.tl.louvain(adata_test)
sc.tl.umap(adata_test)

sc.pl.umap(adata_test, color = 'louvain')

sc.tl.paga(adata_test)
sc.pl.paga(adata_test, color='louvain')
```
![image](https://user-images.githubusercontent.com/26381262/233829778-048055af-c825-4383-adb7-be0c1d83d9e4.png)


According to my understanding, providing a scaled gene expression matrix constitutes an essential input for PAGA analysis, which the Pegasus workflow does not provide by default. I have two plans to solve this:
1. Convert the Pegasus multimodal data object into an AnnData object using the to_anndata() function, then scale the data using sc.pp.scale from Scanpy before executing PAGA.
2. Construct a new scaled matrix with the counts.log_norm matrix and the scale value from Pegasus, or the PCA matrix, then convert this scaled matrix into an AnnData object and perform PAGA. 

I don't know if Plan 1 is meaningful, in fact, I prefer Plan 2, but I don't know how to implement it.
