### ISSUE TITLE
bug in io.py

### ISSUE THREAD

**Issue by xhongyi** [lilab-bcb/pegasus#42]
Hi,

I think I've spotted a bug in io.py

The commit id is: 04d953c706e27d064c242a0e9529544937e1ae42

Line 885:     features_df.to_csv(os.path.join(output_dir, 'features.tsv.gz'), header=None, sep='\t')

This should be features_df.to_csv(os.path.join(output_dir, 'features.tsv.gz'), header=None, sep='\t', index=False)

Otherwise your feature.tsv will have 4 columns isntead of 3 (the first column being a duplicate of the gene name) and the load_one_mtx_file() function will not work.

Please fix!

Thanks,
Hongyi

**Comment by yihming** [comment]
Hi Hongyi,

Thank you very much for pointing out this bug. It's fixed in pull request #43, and will be reflected in the next release.


Sincerely,
Yiming
