### ISSUE TITLE
Change  h5py>=2.10.0 and scipy>=1.3 to be compatible with scanpy

### ISSUE THREAD

**Issue by joshua-gould** [lilab-bcb/pegasus#47]

**Comment by bli25** [comment]
@joshua-gould 

I have checked Pegasus setup.py, there is no restriction on h5py and scipy. Do you want us to make it explicitly?

**Comment by joshua-gould** [comment]
Sorry, I was looking at an old version. Requirements.txt specifies scipy <
1.3 - should we change that? Thanks

**Comment by bli25** [comment]
Hi Josh,

Feel free to change the settings in the requirements.txt. I believe that
file is only used for our travis unit test.

Best,
Bo

Bo Li, Ph.D.
Director, Bioinformatics and Computational Biology Program, Center for
Immunology and Inflammatory Diseases, Massachusetts General Hospital
Member of the Faculty, Harvard Medical School
Associated Scientist, Klarman Cell Observatory, Broad Institute of MIT &
Harvard
149 13th Street, Room 8214, Charlestown, MA 02129

**Comment by yihming** [comment]
`requirements.txt` is now used for `setup.py` only.
