### ISSUE TITLE
Markers in json

### ISSUE THREAD

**Issue by szymczakpau** [lilab-bcb/pegasus#69]
Hi!

I would like to know more about the markers you placed in the json files: 'human_immune', 'mouse_immune', 'human_brain', 'mouse_brain', 'human_lung'. 
Are they manually created or have you used some database such as PanglaoDB?

Best,
Paulina

**Comment by bli25** [comment]
Hi Paulina,

These are manually created based on our collaborators inputs.

Best,
Bo

Bo Li, Ph.D.
Assistant Professor of Medicine, Harvard Medical School
Director, Bioinformatics and Computational Biology Program, Center for
Immunology and Inflammatory Diseases, Massachusetts General Hospital
Associate Member, Broad Institute of MIT & Harvard
149 13th Street, Room 8214, Charlestown, MA 02129
