### ISSUE TITLE
Bug when generating 3D data in (net_tsne/net_fitsne/net_umap) method

### ISSUE THREAD

**Issue by cc-404** [lilab-bcb/pegasus#80]
Hi,
I run the code:"pg.net_tsne(adata, n_components=3)" and got an error: "ValueError: shape mismatch: value array of shape (268,3) could not be broadcast to indexing result of shape (268,2)"

The same error also found in net_fitsne and net_umap method

**Comment by yihming** [comment]
Hi,

Thank you for catching this bug!

It's fixed in [this pull request](https://github.com/klarman-cell-observatory/pegasus/pull/83), and will be reflected in next version.
